# Generated by Django 5.2.7 on 2025-10-20 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'خواننده', 'verbose_name_plural': 'خوانندگان'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'کشور', 'verbose_name_plural': 'کشورها'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'آهنگ', 'verbose_name_plural': 'آهنگ ها'},
        ),
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='music/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac', 'ogg'])], verbose_name='فایل موزیک'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(upload_to='images/artist/', verbose_name='آواتار'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='family',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.artist', verbose_name='خواننده'),
        ),
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='music',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.country', verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='music',
            name='photo',
            field=models.ImageField(upload_to='images/music/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.DateField(verbose_name='تاریخ'),
        ),
    ]
